version: '3'

volumes:
  postgres-data:
    driver: local
  app-gems:
    driver: local

services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rubocop: &app_base
    build: .
    command: guard start --no-bundler-warning --no-interactions --plugin rubocop
    volumes:
      - .:/myapp
      - app-gems:/usr/local/bundle
    depends_on:
      - db

  web:
    <<: *app_base
    command: bundle exec rails s -p 4000 -b '0.0.0.0'
    ports:
      - "4000:4000"
