version: '3'

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
  app-gems:
    driver: local

services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    volumes:
      - redis-data:/data

  rubocop: &app_base
    build: .
    command: guard start --no-bundler-warning --no-interactions --plugin rubocop
    volumes:
      - .:/myapp
      - app-gems:/usr/local/bundle
    depends_on:
      - db
      - redis

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "4080:1080"

  worker:
    <<: *app_base
    command: bundle exec sidekiq

  web:
    <<: *app_base
    command: bundle exec rails s -p 4000 -b '0.0.0.0'
    ports:
      - "4000:4000"
